// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Rate struct {
	ID        int64              `json:"id"`
	Ask       pgtype.Numeric     `json:"ask"`
	Bid       pgtype.Numeric     `json:"bid"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}
