// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	InsertRate(ctx context.Context, arg InsertRateParams) error
}

var _ Querier = (*Queries)(nil)
