// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rates.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRate = `-- name: InsertRate :exec
INSERT INTO rates (ask, bid, fetched_at)
VALUES ($1, $2, $3)
`

type InsertRateParams struct {
	Ask       pgtype.Numeric     `json:"ask"`
	Bid       pgtype.Numeric     `json:"bid"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) InsertRate(ctx context.Context, arg InsertRateParams) error {
	_, err := q.db.Exec(ctx, insertRate, arg.Ask, arg.Bid, arg.FetchedAt)
	return err
}
